name: Deploy blog to gh-pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: ./.github/python-actions
      env:
        PIPENV_VENV_IN_PROJECT: true
      with:
        args: pip install --upgrade pip && pip install -r requirements.txt
    - name: Theme install
      uses: ./.github/python-actions
      with:
        args: git clone https://github.com/gilsondev/pelican-clean-blog.git
    - name: Deploy
      uses: ./.github/python-actions
      with:
        args: ./deploy-to-gh-pages.sh
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
