name: Deploy blog to gh-pages

on:
  workflow_dispatch:
    inputs:
  pull_request:
  push:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files --show-diff-on-failure --color always

  build:
    name: Deploy job
    runs-on: ubuntu-latest
    needs: [pre-commit]
    if: >
      github.ref == 'refs/heads/master' &&
      github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: ./deploy-to-gh-pages.sh
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
