name: Deploy blog to gh-pages

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6.8'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: ./deploy-to-gh-pages.sh
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
